### ISSUE TITLE
Launch Database with proper utf8 support

### ISSUE THREAD

**Issue by thomasfillon** [Parisson/Telemeta#175]
Add the following command line at the end of the mysql container configuration:
`command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci`

This gives:

```
db:
  image: mysql
  volumes:
    - ./scripts/:/srv/scripts
    - ./data/mysql/:/var/lib/mysql
  volumes_from:
    - data
  env_file:
    - env/prod.env
  command: mysqld  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

```
see. #156

and #159 to further convert existing databases.
