### ISSUE TITLE
Installation : TimeSide "Erreur interne du serveur"

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#193]
Following the README installation, with a fresh installation (images and containers), I get the error "Erreur interne du serveur" on TimeSide readers : 

http://147.135.192.114:8050/

**Comment by thomasfillon** [comment]
Hi Anas,

Are you using the master branch of Telemeta ?

**Comment by AnasGhrab** [comment]
I made another branch from the master to store my config these docker-compose.yml modifications : 

```
db:
  image: mysql
  volumes:
    - ./scripts/:/srv/scripts
    - ./data/mysql/:/var/lib/mysql
  volumes_from:
    - data
  env_file:
    - env/prod.env
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

and because I have another process on the 80 port : 

```
nginx:
  image: nginx
  ports:
    - "8050:80"
```
